### ISSUE TITLE
Can't find ~/.gitconfig

### ISSUE THREAD

**Issue by seanism** [dracula/git#2]
Howdy!  I'm not the sharpest crayon in the box.  I can't find the gitconfig file.  Is there another way to install the git theme?

MacOS 11

**Comment by seanism** [comment]
Dingus alert.  Forgot to set global variable in GIT.  Closing.

**Comment by revagomes** [comment]
You're are right. 
After running git config with `--global` flag Git will automatically create your `~/.gitconfig` file.

    git config --global color.ui auto


In case of `~/.gitconfig` file not being present on your home directory and you have not set any global config for Git:

I suggest copying the `config/gitconfig` file from Dracula Git to `~/.gitconfig`. 
This way you will have the base setup for a well organized `.gitconfig` file.

Please notice that git configuration specifically for user.name and user.email are suggested to be placed in another file (private) as advised in the 'INCLUDES'  section of Dracula Git config file.

@see  https://github.com/dracula/git/blob/master/config/gitconfig
